### ISSUE TITLE
Hey! What size of image you use from gym torcs?

### ISSUE THREAD

**Issue by Lukeeeeee** [imagry/Gym-Torcs-DQN#1]
The image given by torcs env only supported 64 * 64 * 3, as I know, also mentioned in this issue:

https://github.com/ugo-nama-kun/gym_torcs/issues/2.

And this size, I believe, is too small to train a deep neural network.

So If there any way I can extract a higher resolution image from gym torcs? Or how did you solve this problem?
Thanks!

**Comment by skariel** [comment]
We use an image size of 256x192, we solved the problem by compressing the image before passing to Python

**Comment by Lukeeeeee** [comment]
But the original image is only 64x64. U mean reshape the 64x64 image to
256x192 image?

**Comment by s271** [comment]
No, we are using modified gym-torcs, original image is 256x192 as set in the options. It described in readme.

**Comment by Lukeeeeee** [comment]
So is there any tutorial about how to use this modified gym torcs? And does it support higher resolution rather than 256x192?
Thanks!

**Comment by larenzhang** [comment]
when I use the interface:obs_vision_to_image_rgb_proto(),there are actually some buffer data.However,I just use: cv2.imdecode(image_jpeg, cv2.CV_LOAD_IMAGE_COLOR),the value of image data becomes zeros totally.
Have you ever encountered similar problems?
Looking forward your respond.Thank you!

**Comment by lyokka** [comment]
same problem 

`
/home/ye/Desktop/gym_torcs/Gym-Torcs-DQN/vtorcs-RL-color/Make-default.mk:680: recipe for target 'subdirs' failed
make[1]: *** [subdirs] Error 1
make[1]: Leaving directory '/home/ye/Desktop/gym_torcs/Gym-Torcs-DQN/vtorcs-RL-color'
Makefile:30: recipe for target 'restart' failed
make: *** [restart] Error 2
`
